### ISSUE TITLE
Use case: Polymer vs LitElement based components benchmarks

### ISSUE THREAD

**Issue by web-padawan** [Polymer/tachometer#139]
Hi, I have a question about using this tool for our purpose at Vaadin.

We would like to setup a sample app similar to `shack` for using in benchmarks test.
But what we need is not to test against older commit, but agains the older version.

So we'd like to test **LitElement-based app agains Polymer-based app**.
Both apps would be implemented using exactly the same components.

Is this doable with `tachometer` at all (using another app as baseline)?

@aomarks I would appreciate any advice on this.

**Comment by aomarks** [comment]
Hi @web-padawan -- you can definitely do this! Actually we have a repo set up at https://github.com/PolymerLabs/benchmarks that does exactly this for 3 implementations of shack done in Polymer 3, LitElement, and a hand-rolled lit-html without custom elements:

```sh
git clone git@github.com:Polymer/benchmarks.git polymer-benchmarks
cd polymer-benchmarks
npm install
npx tachometer --config shack.json
```

It sounds like you could use a similar setup to this for your app. LMK if you need any help setting it up or interpreting the results.

(Here are our results on shack, by the way):

![image](https://user-images.githubusercontent.com/48894/71207647-3634ff80-225c-11ea-9c54-681f2b4020bd.png)

**Comment by web-padawan** [comment]
Thanks! This is exactly what I need 🙂
Closing, will ping you if we have any question s.
