### ISSUE TITLE
How to use with Chromium instead of Chrome?

### ISSUE THREAD

**Issue by marvinhagemeister** [Polymer/tachometer#179]
Chromium is a more popular choice with the Linux crowd in my circles and I was wondering how we can point tachometer to use that. Passing in `chromium` as an argument fails the browser allow-list here:

https://github.com/Polymer/tachometer/blob/88f98064dad8e1f518dd6406bd7529e1955522f7/src/browser.ts#L36-L37

**Comment by aomarks** [comment]
You should be able to set the chrome binary path to whatever you want, and I expect a chromium binary will work. Let me know if it doesn't.

https://github.com/Polymer/tachometer#binary-path-and-arguments

**Comment by marvinhagemeister** [comment]
Thanks for the quick reply! I somehow missed that section :+1:
