### ISSUE TITLE
Disabling autosampling

### ISSUE THREAD

**Issue by guybedford** [Polymer/tachometer#223]
When explicitly setting the number of samples it would be useful to be able to entirely disable autosampling.

This would be an alternative to https://github.com/Polymer/tachometer/issues/221.

Autosampling breaks down when dealing with network testing - I'm simulating a server with network variations here and autosampling is continuning runs after the 1 minute timeout (the lowest possible timeout as well!).

As a result, running a large number of network tests is taking more than 4 hours, when the individual tests should be possible to run within 2 hours.

**Comment by guybedford** [comment]
Reading through the source, I see explicitly setting `timeout: 0` can avoid this batch of 10 which is hard-coded. Note that the docs mention the default timeout is `0` which was why I did not attempt this.

**Comment by aomarks** [comment]
Thanks for the report. I agree this isn't very clear in the docs. I've sent out https://github.com/Polymer/tachometer/pull/224 which hopefully makes this more obvious:

![image](https://user-images.githubusercontent.com/48894/134776941-19b9d5e6-2023-4056-8189-d7ff778db114.png)

**Comment by aomarks** [comment]
You may also be interested in this feature request: https://github.com/Polymer/tachometer/issues/71. I'll bump this up in my priorities, since I think it would improve usability a lot!

**Comment by guybedford** [comment]
Thanks so much for the updates here, that looks very clear to me.
