### ISSUE TITLE
Standalone stats API

### ISSUE THREAD

**Issue by just-boris** [Polymer/tachometer#232]
This module contains [great statistic logic](https://github.com/Polymer/tachometer/blob/main/src/stats.ts) with auto-sampling. However, the public API is strictly requires to use command-line and `selenium-webdriver`.

In our use-case we already have an existing puppeteer setup, which we would like to reuse for the performance testing too.

Currently we have code like this:

```js
import { autoSampleConditionsResolved, computeDifferences, summaryStats } from 'tachometer/lib/stats';

const a = await getResults();
const b = await getResults();

const statsDiff = computeDifferences([
  { stats: summaryStats(a) },
  { stats: summaryStats(b) },
]);

return autoSampleConditionsResolved(statsDiff, { absolute: [50], relative: [0.05] });
```

This works, but does not seem efficient to pull all other harness and dependencies into node_modules. What do you think about publishing the statistic part as a separate module?

**Comment by aomarks** [comment]
I don't think we want to vend a pure statistics library, that's out of scope for us.

**Comment by just-boris** [comment]
Would it be okay, if I extract this code and publish it under my name (preserving the original references, of course)?
